import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Header'
import { RenderModel } from '../components/RenderModel'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
      {/* <RenderModel /> */}
      </main>
    </div>
  )
}

export default Home
